
build: joinProgram.class

joinProgram.class: joinProgram.java
	javac joinProgram.java
	echo  "Note: warning notes come from creating an Array of Arraylists."
	echo  "Run program with format: java joinProgram file1.txt file2.txt joinAttribute1,joinAttribute2"

clean:
	rm joinProgram.class
